server:
  port: 8080

Access-Control-Allow-Origin: http://127.0.0.1:5173/*


mybatis:
  mapper-locations: classpath:com.maboroshi.cave.mapper/*.xml
  type-aliases-package=com: com.maboroshi.cave.mybatis.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cave_tables
    username: root
    password: quin114514
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB


logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug
